/**
 * Canonical static routes for QA, sitemap generation, and ops smoke tests.
 * Dynamic routes use sample paths in DYNAMIC_ROUTE_SAMPLES.
 */

export const SITE_ROUTE_GROUPS = {
  core: 'Core marketplace',
  sell: 'Sell & import',
  trust: 'Trust & legal',
  learn: 'Learn hub',
  collections: 'Collections',
  partners: 'Partners & promos',
  auth: 'Auth',
  account: 'Account',
  ops: 'Owner ops (auth)',
  publicStatic: 'Public static files',
}

/** @type {{ path: string, label: string, group: keyof typeof SITE_ROUTE_GROUPS, auth?: boolean, ops?: boolean }[]} */
export const STATIC_SITE_ROUTES = [
  { path: '/', label: 'Homepage', group: 'core' },
  { path: '/browse', label: 'Browse listings', group: 'core' },
  { path: '/categories', label: 'Categories', group: 'core' },
  { path: '/compare', label: 'Compare marketplaces', group: 'core' },
  { path: '/listing/sample-id', label: 'Listing detail (dynamic)', group: 'core' },
  { path: '/sell', label: 'Sell (policy gate)', group: 'sell' },
  { path: '/sell/start', label: 'List item chooser', group: 'sell' },
  { path: '/sell/coa', label: 'Collectible COA step', group: 'sell' },
  { path: '/sell/import', label: 'eBay / CSV import', group: 'sell' },
  { path: '/sell/dropship-setup', label: 'Dropship setup', group: 'sell' },
  { path: '/sellers', label: 'For sellers / stores', group: 'sell' },
  { path: '/sellers/switch', label: 'Switching guide', group: 'sell' },
  { path: '/seller-tools', label: 'Seller tools', group: 'sell' },
  { path: '/store-builder', label: 'AI store builder', group: 'sell' },
  { path: '/pricing', label: 'Pricing', group: 'sell' },
  { path: '/pay', label: 'Pay & fees', group: 'sell' },
  { path: '/launch-offer', label: 'Launch offer', group: 'sell' },
  { path: '/join/founders10', label: 'FOUNDERS10', group: 'partners' },
  { path: '/join/store-partner', label: 'Store partner', group: 'partners' },
  { path: '/honor', label: 'Honor program', group: 'partners' },
  { path: '/how-it-works', label: 'How it works', group: 'trust' },
  { path: '/protection', label: 'Protection overview', group: 'trust' },
  { path: '/marketplace-policy', label: 'Marketplace policies', group: 'trust' },
  { path: '/terms', label: 'Terms of service', group: 'trust' },
  { path: '/privacy', label: 'Privacy policy', group: 'trust' },
  { path: '/seller-agreement', label: 'Seller agreement', group: 'trust' },
  { path: '/prohibited-items', label: 'Prohibited items', group: 'trust' },
  { path: '/roadmap', label: 'Roadmap', group: 'trust' },
  { path: '/learn', label: 'Learn hub', group: 'learn' },
  { path: '/learn/videos', label: 'Learn videos', group: 'learn' },
  { path: '/learn/tools', label: 'Learn tools index', group: 'learn' },
  { path: '/learn/tools/fee-calculator', label: 'Fee calculator', group: 'learn' },
  { path: '/learn/tools/listing-cost', label: 'Listing cost tool', group: 'learn' },
  { path: '/learn/tools/authenticity-checklist', label: 'Authenticity checklist', group: 'learn' },
  { path: '/learn/tools/coin-study-guide', label: 'Coin study guide', group: 'learn' },
  { path: '/learn/coin-counterfeit-detection-guide', label: 'Article: Coin counterfeits', group: 'learn' },
  { path: '/learn/import-ebay-to-franks-standard', label: 'Article: eBay import', group: 'learn' },
  { path: '/learn/coa-vs-signed-guarantee', label: 'Article: COA vs guarantee', group: 'learn' },
  { path: '/learn/niche-collections-vs-ebay', label: 'Article: Collections vs eBay', group: 'learn' },
  { path: '/learn/seller-playbook', label: 'Article: Seller playbook', group: 'learn' },
  { path: '/collections', label: 'Collections index', group: 'collections' },
  { path: '/collections/graded-sports-cards', label: 'Collection: graded cards', group: 'collections' },
  { path: '/partners', label: 'Partners index', group: 'partners' },
  { path: '/partners/creators', label: 'Creator affiliates', group: 'partners' },
  { path: '/social', label: 'Social promotion', group: 'partners' },
  { path: '/social/community', label: 'Reddit & blog outreach', group: 'partners' },
  { path: '/top-sellers', label: 'Top sellers', group: 'partners' },
  { path: '/video', label: 'Video meetups', group: 'core' },
  { path: '/video/r/demo-room', label: 'Video room (dynamic)', group: 'core' },
  { path: '/verify/coa/FS-2026-000001', label: 'COA verify (dynamic serial)', group: 'trust' },
  { path: '/go/postcard', label: 'Tracked go link', group: 'partners' },
  { path: '/about', label: 'About', group: 'core' },
  { path: '/open-door', label: 'Open door policy', group: 'core' },
  { path: '/contact', label: 'Contact', group: 'core' },
  { path: '/support', label: 'Support', group: 'core' },
  { path: '/download', label: 'Download app', group: 'core' },
  { path: '/dashboard', label: 'Dashboard', group: 'account', auth: true },
  { path: '/order/success', label: 'Order success', group: 'account', auth: true },
  { path: '/auth/login', label: 'Login', group: 'auth' },
  { path: '/auth/register', label: 'Register', group: 'auth' },
  { path: '/auth/verify', label: 'Email verify', group: 'auth' },
  { path: '/ops/panel', label: 'Ops panel', group: 'ops', ops: true },
  { path: '/ops/site-qa', label: 'Full site QA', group: 'ops', ops: true },
  { path: '/ops/test-checkout', label: 'Checkout QA', group: 'ops', ops: true },
  { path: '/ops/status', label: 'Transaction readiness', group: 'ops', ops: true },
  { path: '/ops/authenticity', label: 'Authenticity ops', group: 'ops', ops: true },
  { path: '/ops/refunds', label: 'Forced refunds ops', group: 'ops', ops: true },
  { path: '/ops/marketing', label: 'Marketing ops', group: 'ops', ops: true },
  { path: '/ops/dropship', label: 'Dropship ops', group: 'ops', ops: true },
  { path: '/ops/ads', label: 'Social ads ops', group: 'ops', ops: true },
  { path: '/ops/google-ads', label: 'Google ads ops', group: 'ops', ops: true },
  { path: '/ops/influencers', label: 'Influencers ops', group: 'ops', ops: true },
  { path: '/ops/social-promo', label: 'Social promo ops', group: 'ops', ops: true },
  { path: '/ops/niche-collections', label: 'Niche collections ops', group: 'ops', ops: true },
  { path: '/ops/sellers-phone', label: 'Sellers phone ops', group: 'ops', ops: true },
  { path: '/ops/ebay-prospects', label: 'eBay prospects', group: 'ops', ops: true },
  { path: '/ops/mail-prospects', label: 'Mail prospects', group: 'ops', ops: true },
  { path: '/ops/mail-setup', label: 'Mail setup', group: 'ops', ops: true },
  { path: '/ops/find-sellers', label: 'Find sellers redirect', group: 'ops', ops: true },
  { path: '/ops/seller-lookup', label: 'Seller lookup (desktop)', group: 'ops', ops: true },
  { path: '/seller-lookup', label: 'Seller lookup (legacy redirect)', group: 'ops', ops: true },
  { path: '/mail/postcard-design.html', label: 'Postcard design HTML', group: 'publicStatic' },
]

export function routesByGroup () {
  const out = {}
  for (const r of STATIC_SITE_ROUTES) {
    if (!out[r.group]) out[r.group] = []
    out[r.group].push(r)
  }
  return out
}
